# Generated by Django 5.1 on 2024-11-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='timesTamp',
            new_name='timestamp',
        ),
    ]
